version: '3'
services:
  postgres:
    container_name: postgres_container
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - opnet
    ports:
      - '5432'
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 50
    ports:
      - "5050:50"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - opnet
  rabbitmq:
    container_name: rabbit_container
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
  service-discovery-server:
    container_name: service-discovery-server
    image: service-discovery-server:latest
    ports:
      - "8761:8761"
    depends_on:
      - postgres
    networks:
      - opnet

  api-gateway:
      container_name: api-gateway
      image: api-gateway:latest
      environment:
        - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
      ports:
        - "8080:8080"
      depends_on:
        - service-discovery-server
      networks:
        - opnet
  user-service:
      container_name: user-service
      image: user-service:latest
      environment:
        - SPRING_PROFILES_ACTIVE=docker
        - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
      ports:
        - "8081:8081"
      deploy:
        restart_policy:
          condition: on-failure
      depends_on:
        - service-discovery-server
      networks:
        - opnet
  recensione-service:
    container_name: recensione-service
    image: recensione-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8082:8082"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - service-discovery-server
    networks:
      - opnet
  negozio-service:
    container_name: negozio-service
    image: negozio-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8083:8083"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - service-discovery-server
    networks:
      - opnet
  gestore_ordini-service:
    container_name: gestore_ordini-service
    image: gestore_ordini-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8084:8084"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - service-discovery-server
    networks:
      - opnet
  annuncio-service:
    container_name: annuncio-service
    image: annuncio-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8085:8085"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - service-discovery-server
    networks:
      - opnet
networks:
    opnet:
      driver: bridge


