version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
  service-discovery-server:
    container_name: service-discovery-server
    image: service-discovery-server:latest
    ports:
      - "8761:8761"
    networks:
      - opnet

  api-gateway:
      container_name: api-gateway
      image: api-gateway:latest
      environment:
        - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
      ports:
        - "8080:8080"
      depends_on:
        - service-discovery-server
      networks:
        - opnet
  user-service:
      container_name: user-service
      image: user-service:latest
      environment:
        - SPRING_PROFILES_ACTIVE=docker
        - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
      ports:
        - "8081:8081"
      deploy:
        restart_policy:
          condition: on-failure
      depends_on:
        - service-discovery-server
      networks:
        - opnet
  recensione-service:
    container_name: recensione-service
    image: recensione-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - eureka.client.serviceUrl.defaultZone=http://service-discovery-server:8761/eureka/
    ports:
      - "8082:8082"
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - service-discovery-server
    networks:
      - opnet

networks:
    opnet:
      driver: bridge


